[package]
name = "dtkit-patch"
version = "0.1.3"
authors = ["ManShanko <deathage@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ManShanko/dtkit-patch"

[dependencies]
steam_find = { git = "https://github.com/ManShanko/steam_find", rev = "8195dd0e8fff2a3cedf94fe130a9a08cbe70839e" }
winreg = "0.10.1"
