[package]
name = "dtkit-patch"
version = "0.1.0"
authors = ["ManShanko <deathage@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ManShanko/dtkit-patch"

[dependencies]
steam_find = { git = "https://github.com/ManShanko/steam_find", rev = "1c951920461a02eab72e2bb92512da541a716e75" }
