# adapted from ripgrep's release.yml:
# https://github.com/BurntSushi/ripgrep/blob/4386b8e805e273a9795ad4e256c455c74407c949/.github/workflows/release.yml

name: release
on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-22.04
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
      app_version: ${{ env.APP_VERSION }}
    steps:
      - name: Get release version from tag
        shell: bash
        if: env.APP_VERSION == ''
        run: |
          echo "APP_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "version is: ${{ env.APP_VERSION }}"
      - name: Create GitHub release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.APP_VERSION }}
          release_name: ${{ env.APP_VERSION }}

  build-release:
    name: build-release
    needs: ['create-release']
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [win]
        include:
        - build: win
          os: windows-latest
          target: x86_64-pc-windows-msvc

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        target: ${{ matrix.target }}
        components: rust-src

    - name: Build release binary
      run: cargo build --verbose --release --target ${{ matrix.target }} "-Zbuild-std=std,panic_abort" "-Zbuild-std-features=,"

    - name: Strip release binary (linux)
      if: matrix.build == 'linux'
      run: strip "target/${{ matrix.target }}/release/dtkit-patch"

    - name: Create archive
      shell: bash
      run: |
        staging="dtkit-patch-${{ needs.create-release.outputs.app_version }}-${{ matrix.target }}"
        mkdir -p "$staging"

        cp README.md "$staging/"

        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cp "target/${{ matrix.target }}/release/dtkit-patch.exe" "$staging/"
          7z a "$staging.zip" "./$staging/*"
          echo "ASSET=$staging.zip" >> $GITHUB_ENV
        else
          cp "target/${{ matrix.target }}/release/dtkit-patch" "$staging/"
          tar czf "$staging.tar.gz" "./$staging/*"
          echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV
        fi

    - name: Upload release archive
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ${{ env.ASSET }}
        asset_name: ${{ env.ASSET }}
        asset_content_type: application/octet-stream